"""
verify_rng.py — confirms DotNetRandom matches System.Random from Unity's Mono build.

Two verification paths:

PATH A — against hardcoded reference vectors
  Generated by compiling VerifyRng.cs with Unity's bundled Mono (6.x, MonoBleedingEdge)
  and running it via:
    MONO=/Applications/Unity/Hub/Editor/6000.2.7f2/Unity.app/Contents/MonoBleedingEdge/bin/mono
    MCS=.../mcs
    $MCS -out:/tmp/VerifyRng.exe VerifyRng.cs && $MONO /tmp/VerifyRng.exe
  Vectors verified 2026-05-15 against Unity 6000.2.7f2.
  Run: python verify_rng.py

PATH B — live comparison against Unity's Mono
  If Unity is installed at the standard path, compiles and runs VerifyRng.cs dynamically.
  Run: python verify_rng.py --live
"""

import sys
import os
import subprocess
import importlib.util

_HERE   = os.path.dirname(os.path.abspath(__file__))
_PARENT = os.path.dirname(_HERE)

spec = importlib.util.spec_from_file_location(
    "dotnet_random", os.path.join(_PARENT, "dotnet_random.py"))
mod  = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
DotNetRandom = mod.DotNetRandom

# ── Reference vectors — generated by Unity's Mono (MonoBleedingEdge 6.x) ─────
# Produced by VerifyRng.cs, 2026-05-15, Unity 6000.2.7f2
REFERENCE = {
    0: [0.72624326996795985,0.81732535959096875,0.76802268939466345,0.5581611914365372,0.2060331540210327,0.55888479461841511,0.90602706601192573,0.44217787331071584,0.97754975314137982,0.27370445768987034,0.29190628476995334,0.46731470034798361,0.63265907281667877,0.46951187842968473,0.98215125314060192,0.030366990729406004,0.86237015382497118,0.99534708121574811,0.67718114921691885,0.31459179302425672],
    1: [0.24866858415709278,0.11074397718102856,0.46701067987224587,0.77160412202198247,0.657518893786482,0.43278260130099144,0.35408376360036609,0.94386227612563511,0.10126645355544353,0.64245555533210541,0.028636812711431092,0.24802914552764463,0.32011013166984081,0.989767147689018,0.68212311886349841,0.65488788702287148,0.28272922396786943,0.61534640826999509,0.70425153556477815,0.70179667542772217],
    42: [0.66810646591154232,0.14090729837348093,0.12551828945312568,0.52276427602524134,0.16843422416990353,0.26259267528662117,0.72440836472642067,0.51292279153732712,0.17365117053205667,0.76125055866374192,0.23458845831201805,0.25732139789374608,0.50560354464948343,0.3202331873216821,0.38096961350225361,0.26024463505495554,0.51745109982669868,0.0353188174941199,0.8141373758270114,0.57719685396980347],
    -1: [0.24866858415709278,0.11074397718102856,0.46701067987224587,0.77160412202198247,0.657518893786482,0.43278260130099144,0.35408376360036609,0.94386227612563511,0.10126645355544353,0.64245555533210541,0.028636812711431092,0.24802914552764463,0.32011013166984081,0.989767147689018,0.68212311886349841,0.65488788702287148,0.28272922396786943,0.61534640826999509,0.70425153556477815,0.70179667542772217],
    12345: [0.066746934813795109,0.070159508879370752,0.77476513514982781,0.51113926875923721,0.79749055849271389,0.827308291023275,0.16595879530811627,0.73613062348967917,0.26021636475818993,0.5060048510814108,0.23027372231254062,0.38714044326317515,0.21598061510174563,0.020810884898906055,0.13483360229750796,0.740831733560577,0.19509106790418321,0.88703956589430555,0.861100613540551,0.35886506380460459],
    999999999: [0.39295087074532681,0.11396655585335873,0.546617134263095,0.93016359905254264,0.519996720142661,0.36756332328895264,0.046410724076633679,0.7554127870851256,0.26789678785386345,0.54718839775174311,0.49665348767147094,0.86626126704097783,0.79837002828641335,0.20858987942737986,0.0050758561143073519,0.69931155987983173,0.58490935926554233,0.42959470089040452,0.99797010933885821,0.330852309395956],
    -2147483648: [0.72624326996795985,0.81732535959096875,0.76802269218863117,0.5581611914365372,0.2060331540210327,0.55888479368709254,0.90602706601192573,0.44217787331071584,0.97754975314137982,0.27370445210193489,0.29190628476995334,0.46731470034798361,0.63265906629742075,0.46951187842968473,0.98215125314060192,0.030366990729406004,0.86237014451174543,0.99534708121574811,0.67718114921691885,0.3145917790544181],
}

N = 20

UNITY_MONO = (
    "/Applications/Unity/Hub/Editor/6000.2.7f2/Unity.app"
    "/Contents/MonoBleedingEdge/bin/mono"
)
UNITY_MCS = UNITY_MONO.replace("/mono", "/mcs")

def run_python(seed):
    rng = DotNetRandom(seed)
    return [rng.next_double() for _ in range(N)]

def run_live_mono(seeds):
    cs_path = os.path.join(_HERE, "VerifyRng.cs")
    exe     = "/tmp/VerifyRng_verify.exe"
    try:
        subprocess.check_call([UNITY_MCS, f"-out:{exe}", cs_path],
                              stderr=subprocess.DEVNULL)
        out = subprocess.check_output([UNITY_MONO, exe],
                                      stderr=subprocess.DEVNULL, text=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        return None, str(e)
    results = {}
    for line in out.strip().splitlines():
        seed_str, vals_str = line.split(":", 1)
        s = int(seed_str.split("=")[1].strip())
        results[s] = [float(v) for v in vals_str.strip().split(",")]
    return results, None

def compare(seed, py_vals, ref_vals):
    mismatches = [(i, py_vals[i], ref_vals[i])
                  for i in range(N) if py_vals[i] != ref_vals[i]]
    if mismatches:
        print(f"  seed={seed:12d}: FAIL — {len(mismatches)}/{N} mismatch(es)")
        for i, got, want in mismatches[:3]:
            print(f"    [{i}] got={got!r}  want={want!r}")
        return False
    print(f"  seed={seed:12d}: PASS ({N}/{N} exact)")
    return True

if __name__ == "__main__":
    live = "--live" in sys.argv
    print("=== DotNetRandom verification ===")
    print(f"    Python port: {os.path.join(_PARENT, 'dotnet_random.py')}\n")

    if live:
        print("PATH B — live Unity Mono comparison")
        ref, err = run_live_mono(list(REFERENCE.keys()))
        if ref is None:
            print(f"  Unity Mono not available ({err})\n  Falling back to PATH A.\n")
            live = False
        else:
            print(f"  Runtime: {UNITY_MONO}\n")
            passed = sum(compare(s, run_python(s), ref[s]) for s in ref)
            total  = len(ref)

    if not live:
        print("PATH A — hardcoded vectors from Unity Mono 6.x (2026-05-15)\n")
        passed = sum(compare(s, run_python(s), v) for s, v in REFERENCE.items())
        total  = len(REFERENCE)

    print(f"\n{'PASS' if passed == total else 'FAIL'}: {passed}/{total} seeds matched exactly.")
    if passed < total:
        print("DotNetRandom does not match Unity Mono System.Random — reconstruction invalid.")
        sys.exit(1)
    else:
        print("DotNetRandom verified against Unity Mono System.Random.")
        print("Dot position reconstruction from VRDots seeds is valid.")
